# Example goseek configuration

env_config: {
        FILENAME: /home/za27933/tess/goseek-challenge/simulator/goseek-v0.1.4.x86_64,
        SCENES: [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
        video_log_path: "/home/za27933/tess/tesse-gym/goseek-videos/goseek-debug-v7",
        collision_reward: -0.1,
        scene_graph: {"1": "/home/za27933/tess/tesse-gym/data/scene_graphs/scene_graph_01_v0.1.pkl",
                      "2": "/home/za27933/tess/tesse-gym/data/scene_graphs/scene_graph_02_v0.1.pkl",
                      "3": "/home/za27933/tess/tesse-gym/data/scene_graphs/scene_graph_03_v0.1.pkl",
                      "4": "/home/za27933/tess/tesse-gym/data/scene_graphs/scene_graph_04_v0.1.pkl",
                    }
    }

model: {
        custom_model: nature_cnn_rnn,
        custom_model_config: {
            cnn_shape: [5, 120, 160],
            rnn_type: GRU,
            hidden_size: 512,
            pose_length: 3,
            graph_node_features: 3,
            graph_conv_features: [16, 32, 64, 128],
            graph_pooling_method: "GlobalAttention",
            cat_pose_to_gcn: True,
        },
        max_seq_len: 400,
    }

# training 
lr : grid_search([2.5e-5])
gamma : grid_search([0.995])
lambda : grid_search([0.95])
vf_loss_coeff : 0.25
clip_param : 0.2
vf_clip_param : 75
vf_share_layers : True
entropy_coeff : 0.01
    
# batch 
train_batch_size : 512 
sgd_minibatch_size : 128
num_sgd_iter : 8

# env 
env : goseek
framework : torch
num_workers : 3
num_gpus : 4
num_envs_per_worker : 1
log_level : INFO

evaluation_interval : 200
evaluation_num_episodes : 100
evaluation_config: {
    env_config: {
            SCENES: [5],
            FILENAME: /home/za27933/tess/goseek-challenge/simulator/goseek-v0.1.4.x86_64,
            RANK: 6,
            scene_graph: {"5": "/home/za27933/tess/tesse-gym/data/scene_graphs/scene_graph_05_v0.1.pkl"}
        }
    }
